services:
  - type: web
    name: Sentilizer
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        fromSecret: SECRET_KEY
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
